- gmm/gmm_message/build.go
For security Protected NAS messages the Security Header Type IE of the Plain 5GS NAS message has to be set to Plain.
TS 24.501: 8.2.28.1 and 9.9
This IE includes a complete plain 5GS NAS message as specified in subclauses 8.2 and 8.3. The SECURITY PROTECTED 5GS NAS MESSAGE message (see subclause 8.2.28) is not plain 5GS NAS messages and shall not be included in this IE.
> FIX security header of inner NAS message

- gmm/handler.go
This fixes error handling of the case of "nsiInformation == nil".
See https://github.com/am677/amf/commit/6f4554aed3b3b8981425357d49ae6ff9c03f69e7#diff-d18bc03b6c298e8f0f1807f19bcd8610L289-L312
before
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xaf2803]
goroutine 22 [running]:
free5gc/src/amf/gmm.selectSmf(0xc0000d4000, 0xdd29a3, 0xb, 0xc00071e5a0, 0xc000856a28, 0x8, 0x8, 0xc0008cbcd0, 0x198, 0x198, ...)
/home/user/go/src/free5gc/src/amf/gmm/handler.go:312 +0x293
```
<details><summary>detail</summary><div>
```
INFO[2020-06-05T15:17:35+09:00]/src/amf/nas/nas_security/security.go:37 free5gc/src/amf/nas/nas_security.Encode() NasPdu Security: Integrity Protected And Ciphered  AMF=NAS …
```
> Fix NSSelectionGetForPduSession error handling

- gmm/message/build.go
The correct header must be plain in inner 5GS message
> AMF fails to set NAS security header in service accept

- gmm/handler.go
AMF panics at HandleRegistrationComplete when Mobility/PeriodicUpdateRegistration.
Since it refer to freed RegistrationRequestData.
> AMF panics at HandleRegistrationComplete when Mobility/PeriodicUpdateRegistration

- ngap/message/build.go
AMF fails to decode id-UERadioCapability in InitialContextSetupRequest due to parsing is done in string not hex.
> AMF fails to decode id-UERadioCapability in InitialContextSetupRequest

- ngap/message/send.go
```
2020-12-03T08:50:04Z [INFO][AMF][Init] Terminating AMF...
2020-12-03T08:50:04Z [INFO][AMF][Consumer] [AMF] Send Deregister NFInstance
2020-12-03T08:50:05Z [INFO][AMF][Init] [AMF] Deregister from NRF successfully
2020-12-03T08:50:05Z [INFO][AMF][Init] Send AMF Status Indication to Notify RANs due to AMF terminating
2020-12-03T08:50:05Z [INFO][AMF][NGAP] [AMF] Send AMF Status Indication
2020-12-03T08:50:05Z [INFO][AMF][NGAP] [AMF] Build AMF Status Indication message
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xb7c409]
goroutine 50 [running]:
free5gc/src/amf/ngap/message.SendToRan(0xc00018b490, 0xc000328640, 0x13, 0x20)
/root/go/src/free5gc/src/amf/ngap/message/send.go:34 +0x79 …
```
> fix send to ran panic

- context/amf_ue.go
AMF Registration Status Update Error happens when AMF receives Registration Request with Requested NSSAI.
> AMF Registration Status Update Error happens

- gmm/message/send.go
Even after receiving UEContext Release, AMF keep on resending Registration Accept message.  That is not conforms to the specification and it even cause a crash.
> AMF Resend Registration Accept even after receiving UEContext Release

- gmm/handler.go
AMF uses DeepEqual between pointer with entity when comparing TargetAmfSet in  handleRequestedNssai().
> AMF DeepEqual between pointer with entity bug.

- ngap/message/send.go
We need to call recover() when exiting SendToRan().
> AMF panics when retransmission processing of Registration Accept

- gmm/handler.go
Skip decoding NAS message in NAS message container IE in Registration Request(GUTI) when NAS MAC verification is failed.
> Fix: AMF fails to decode Registration Request(GUTI)

- gmm/handler.go
HandleAuthenticationFailure() include RAND in AuthenticateRequest message when handling of SynchFailure case described in TS 24.501 5.4.1.3.7 case f.
> HandleAuthenticationFailure() include RAND in AuthenticateRequest

- consumer/sm_context.go
- context/context.go
- factory/config.go
- util/init_context.go
This PR makes AMF to select SMF by locality.
If locality is missing, AMF selects SMF in a similar way so far.
> Add locality in config and select SMF by locality

- gmm/handler.go
If the UE state is "Deregistered", the Mobility/Periodic Update process continues.
modify "implicitly de-registered" to reject.
TS 24.501
5.5.1.3.5 Mobility and periodic registration update not accepted by the network
10 (implicitly de-registered).
> Fix: Responds to SecurityModeReject in a mobility update

- gmm/handler.go
There is no transition for Authentication state when receiving the  GMMEvent SecurityModeSuccess.
And in this case, this GMMEvent is sent when UE passes EAP-AKA' authentication, so it should be AuthSuccessEvent.
> fix FSM transition error when use EAP-AKA'

- gmm/handler.go
The registration request's Mobility Registration Update,
Periodic Registration Update, and Emergency Registration key updates are missing.
Modify the key to be updated during the Mobility and Periodic Registration Updating.
Not Supportted Emergency Registration.
Note:3GPP TS33.501
6.8.1.2.1 Transition from CM-IDLE to CM-CONNECTED
6.8.1.2.2 Establishment of keys for cryptographically protected radio bearers in 3GPP access
> Fix: KgNB not updated during CM-IDLE to CM-CONNECTED transition

- gmm/handler.go
- gmm/message/build.go
- gmm/message/send.go
AMF sends unciphered identity request after NAS security procedure.
reference github issue: [#195](https://github.com/free5gc/free5gc/issues/195)
> fix(amf): AMF sends unciphered identity request

- gmm/handler.go
- ngap/handler.go
Null pointer may happen when executing consecutive pdu releases
> fix (amf):  fix null pointer exception

- context/amf_ue.go
- context/context.go
- factory/config.go
- gmm/handler.go
- gmm/message/send.go
- gmm/sm.go
- util/init_context.go
This PR modify thing below in current identification procedure:
- Support retransmission of identity request with timer T3570.
- Check the received identity type is equal to the one in request message.
> support retransmission of identity request and receicved type check

- gmm/handler.go
This PR makes AMF to select PCF by locality.
If locality is missing, AMF selects PCF in a similar way so far.
> Select PCF by locality

- context/amf_ran.go
- context/amf_ue.go
- context/ran_ue.go
- gmm/sm.go
- ngap/handler.go
- When AttachRanUe()/DetatchRanUe() is executed, it is modified to set the log information.
- When Ran information is switched by SwitchToRan(), the log information is also updated.
- Changed to put RanUeNgapID in NGAP Handler log as much as possible.
> Fix: Log information is not updated

- internal/nas/handler.go
- internal/nas/nas_security/fuzz_test.go
- internal/nas/nas_security/security.go
- internal/ngap/handler.go
- internal/sbi/producer/callback.go
Refine functions nas_security.Encode and nas_security.Decode according to TS24.501 security specification
At decoding, if the following elements do not meet the conditions of the TS24.501, this message is treated as error.
- Message type
- NAS security header type
- Whether valid security context is existed?
- Result of integrity check
- Is message initial message?
> Refine nas_security

- go.mod
- go.sum
- internal/gmm/handler.go
- internal/gmm/message/build.go
- internal/nas/fuzz_test.go
- internal/nas/testdata/fuzz/FuzzHandleNAS/046f199c68fe1f53
- internal/nas/testdata/fuzz/FuzzHandleNAS/3456a554a218310c
- internal/nas/testdata/fuzz/FuzzHandleNAS/cf35851f610160df
- internal/nas/testdata/fuzz/FuzzHandleNAS2/116c4732855a96fe
- internal/nas/testdata/fuzz/FuzzHandleNAS2/93a78ca68a21fa7e
- internal/nas/testdata/fuzz/FuzzHandleNAS2/973a10096b0e3ac2
- internal/sbi/consumer/nf_discovery.go
Add fuzzing code for HandleNAS().
Add check of mobile identity and other fields in NAS message to resolve crash issue by fuzzing of HandleNAS().
Require https://github.com/free5gc/nas/pull/19.
> Fuzzing for HandleNAS

- internal/gmm/message/build.go
- internal/gmm/message/send.go
Some NAS messages are always sent as plain messages regardless of security context is valid.
This is incorrect behavior that violates NAS specifications.
This PR fix this.
> All build functions use nas_security.Encode()

- go.mod
- go.sum
- internal/ngap/dispatcher.go
- internal/ngap/message/send_test.go.test
- internal/ngap/service/service.go
Module **sctp** is moved to free5gc now.
> module: use free5gc/sctp instead of calee/sctp

- internal/gmm/handler.go
- internal/sbi/producer/callback/n1n2message.go
The current implementation does not consider the case of  Namf_Communication_N1MessageNotify failure.
In this case, I think AMF should send a NAS reroute message to UE.
This patch has been verified by the it_test.
> send reroute nas msg if SendN1MessageNotifyAtAMFReAllocation failed

- .github/workflows/commit-msg-check.yml
- .github/workflows/golangci-lint.yml
- .golangci.yml
- internal/nas/nas_security/security.go
This pull request adds CI Action to check whether commit messages follow [Conventional Commit Messages](https://www.conventionalcommits.org/en/v1.0.0/) or not. 
- https://github.com/webiny/action-conventional-commits 
- https://www.conventionalcommits.org/en/v1.0.0/
> chore: create commit-msg-check.yml

- internal/sbi/processor/event_exposure.go
Fix for issue: https://github.com/free5gc/free5gc/issues/579
> fix: AMF returned 500 Internal Server Error for a Event Exposure POST API request #579

- internal/context/amf_ran.go
- internal/context/ran_ue.go
- internal/gmm/common/user_profile.go
- internal/nas/handler.go
- internal/ngap/handler.go
This PR fixes the issue that if the UE is in CM-Idle state, the UE initiating ServiceRequest will require authentication again. 
- Related PR #136 
- Rename `FindAmfUE` to `HoldingAmfUe`
> fix: HoldingAmfUe restore when CM-Idle

- internal/sbi/consumer/ausf_service.go
The current AMF does not use the AuthctxId received from the AUSF during authentication but directly uses Ue.Suci.
---------------------------------------
1. 5g-aka
2. EAP-based authentication method
> fix: use authctxId to authentication 

- internal/gmm/common/user_profile.go
- internal/ngap/handler.go
In free5GC v3.4.3, during an N2 handover, two "release UE context" messages are sent, causing an error during the second "handle release UE context complete."
---
Before the fix, when running ./test.sh TestN2Handover, the result is as shown in the picture.
The system sends the "release UE context" twice, but since the test function only handles it once, no error occurs.
---
After the fix, when running ./test.sh TestN2Handover, the result is as shown in the picture, and only one "release UE context" is sent.
https://github.com/free5gc/free5gc/issues/604
> fix: release twice uecontext when handover

- internal/context/amf_ran.go
- internal/gmm/handler.go
In TS 23.502 section 4.2.2.1, it is mentioned 
```
the AMF determines the Access Type and RAT Type as defined in clause 5.3.2.3 of TS 23.501 [2]. 
```
However, the current AMF has not yet determined ue.rattype, which has caused ue.rattype to remain empty.
---
In TS 23.501 section 5.3.2.3 Registration Area management 
```
For 3GPP access the AMF determines the RAT type the UE is camping on based on the Global RAN Node IDs 
associated with the N2 interface and additionally the Tracking Area indicated by NG-RAN.
```
---
Global RAN Node ID is define in TS 38.413
> fix: amf determine ue.rattype in registration

- internal/sbi/consumer/amf_service.go
Fix #146 .
Change Guti to Supi in CreateUEContextRequest.
closes #146
> Fix: change guti to supi in CreateUEContextRequest

- internal/nas/nas_security/security.go
This PR is for [#713](https://github.com/free5gc/free5gc/issues/713).
> fix: getSecurityHeaderType
